apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha
    chart: redis-ha-3.0.1
    heritage: Tiller
    release: redis-k8s
  name: redis-k8s-redis-ha-svc
  namespace: redis
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app: redis-ha
    release: redis-k8s
  type: LoadBalancer
